# Generated by Django 6.1 on 2026-08-14 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('prompt_version', models.CharField(max_length=20)),
                ('raw_response', models.TextField(blank=True)),
                ('parsed_ok', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True)),
                ('latency_ms', models.IntegerField(blank=True, null=True)),
                ('input_tokens', models.IntegerField(blank=True, null=True)),
                ('output_tokens', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='emails.emailmessage')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExtractedTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_payload', models.JSONField(default=dict)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('is_all_day', models.BooleanField(default=False)),
                ('assignee', models.CharField(blank=True, max_length=255)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('synced', 'Synced to calendar')], db_index=True, default='pending', max_length=20)),
                ('was_edited', models.BooleanField(default=False)),
                ('edited_fields', models.JSONField(blank=True, default=list)),
                ('calendar_event_id', models.CharField(blank=True, max_length=255, null=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='emails.emailmessage')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='extraction.extractionrun')),
            ],
            options={
                'ordering': ['due_at', '-created_at'],
            },
        ),
    ]
