# Generated by Django 6.1 on 2026-08-16 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extraction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractedtask',
            name='attendee_emails',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='extractedtask',
            name='invite_attendees',
            field=models.BooleanField(default=False),
        ),
    ]
