# Generated by Django 6.1 on 2026-08-14 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(db_index=True, max_length=998, unique=True)),
                ('uid', models.IntegerField(blank=True, null=True)),
                ('folder', models.CharField(default='INBOX', max_length=255)),
                ('subject', models.CharField(blank=True, max_length=998)),
                ('sender_name', models.CharField(blank=True, max_length=255)),
                ('sender_email', models.CharField(blank=True, max_length=320)),
                ('recipients', models.JSONField(blank=True, default=list)),
                ('body_text', models.TextField(blank=True)),
                ('body_html', models.TextField(blank=True)),
                ('raw_source', models.BinaryField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('fetched', 'Fetched'), ('analyzing', 'Analyzing'), ('analyzed', 'Analyzed'), ('failed', 'Failed')], db_index=True, default='fetched', max_length=20)),
                ('error', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
    ]
